#pragma once

// state_history.h is generated by Python with the Jinja 2 template
// do not manually modify state_history.h

#include <algorithm>
#include <cstring>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <flecs.h>

// NOTE: Component structs must be defined before including this header

// Operation types for event sourcing
enum class ComponentOp : uint8_t {
  Add = 0,    // Component added to entity (stores full data)
  Remove = 1, // Component removed from entity (no data)
  Set = 2     // Component modified (stores XOR diff)
};

// Compact header for each component operation in the buffer
struct ComponentHeader {
  flecs::entity_t entity;
  flecs::entity_t component;
  uint16_t size;      // Data size (0 for Remove operations)
  uint16_t offset;    // Offset in data section
  ComponentOp op;     // Operation type
  uint8_t padding[3]; // Padding for alignment
};

// Header for relationship operations (pairs)
struct RelationshipHeader {
  flecs::entity_t entity;   // Source entity
  flecs::entity_t relation; // Relationship type
  flecs::entity_t target;   // Target entity
  ComponentOp op;           // Add or Remove (relationships don't use Set)
  uint8_t padding[4];       // Padding for alignment
};

// Flag bits for Snapshot
enum SnapshotFlags : uint8_t {
  FLAG_IS_KEYFRAME = 1 << 0,
  FLAG_COMPONENT_COMPRESSED = 1 << 1,
  FLAG_ENTITY_COMPRESSED = 1 << 2,
  FLAG_RELATIONSHIP_COMPRESSED = 1 << 3
};

struct Snapshot {
  uint32_t frame;
  uint8_t flags;
  std::vector<uint8_t>
      buffer; // Combined buffer: [header][components][entities][relationships]
  uint32_t total_uncompressed_size; // For stats only

  Snapshot() : frame(0), flags(0), total_uncompressed_size(0) {}

  bool is_keyframe() const { return flags & FLAG_IS_KEYFRAME; }
  void set_keyframe(bool value) {
    if (value)
      flags |= FLAG_IS_KEYFRAME;
    else
      flags &= ~FLAG_IS_KEYFRAME;
  }

  bool is_component_compressed() const {
    return flags & FLAG_COMPONENT_COMPRESSED;
  }
  void set_component_compressed(bool value) {
    if (value)
      flags |= FLAG_COMPONENT_COMPRESSED;
    else
      flags &= ~FLAG_COMPONENT_COMPRESSED;
  }

  bool is_entity_compressed() const { return flags & FLAG_ENTITY_COMPRESSED; }
  void set_entity_compressed(bool value) {
    if (value)
      flags |= FLAG_ENTITY_COMPRESSED;
    else
      flags &= ~FLAG_ENTITY_COMPRESSED;
  }

  bool is_relationship_compressed() const {
    return flags & FLAG_RELATIONSHIP_COMPRESSED;
  }
  void set_relationship_compressed(bool value) {
    if (value)
      flags |= FLAG_RELATIONSHIP_COMPRESSED;
    else
      flags &= ~FLAG_RELATIONSHIP_COMPRESSED;
  }

  size_t memory_size() const { return sizeof(Snapshot) + buffer.capacity(); }

  // Buffer layout:
  // [6 x uint32_t header: component_size, component_uncomp, entity_size,
  // entity_uncomp, rel_size, rel_uncomp] [component data] [entity data]
  // [relationship data]

  struct SectionInfo {
    uint32_t size;
    uint32_t uncompressed_size;
    uint32_t offset; // Calculated from header
  };

  SectionInfo get_component_info() const;

  SectionInfo get_entity_info() const;

  SectionInfo get_relationship_info() const;

  std::vector<uint8_t> get_decompressed_buffer() const;

  size_t header_count() const;

  const ComponentHeader *
  get_header(size_t index,
             const std::vector<uint8_t> &decompressed_buffer) const;

  const uint8_t *
  get_data(const ComponentHeader *header,
           const std::vector<uint8_t> &decompressed_buffer) const;

  std::vector<uint8_t> get_decompressed_relationships() const;

  std::vector<RelationshipHeader> decode_relationships() const;

  std::vector<uint8_t> get_decompressed_entities() const;

  struct EntityLifecycle {
    std::vector<std::pair<flecs::entity_t, std::string>> entities_created;
    std::vector<flecs::entity_t> entities_destroyed;
    std::unordered_set<flecs::entity_t> existing_entities;
  };

  EntityLifecycle decode_entities() const;
};

// Helper to get component size
struct ComponentRegistry {
  std::unordered_map<flecs::entity_t, size_t> component_sizes;

  void register_component(flecs::entity_t id, size_t size) {
    component_sizes[id] = size;
  }

  size_t get_size(flecs::entity_t id) const {
    auto it = component_sizes.find(id);
    return it != component_sizes.end() ? it->second : 0;
  }
};

// Track component operations that occurred this frame
struct ComponentEvent {
  flecs::entity_t entity;
  flecs::entity_t component;
  ComponentOp op;
};

// Track relationship operations that occurred this frame
struct RelationshipEvent {
  flecs::entity_t entity;   // Source entity
  flecs::entity_t relation; // Relationship type
  flecs::entity_t target;   // Target entity
  ComponentOp op;           // Add or Remove
};

// Track entity lifecycle events
enum class EntityOp : uint8_t { Create = 0, Destroy = 1 };

struct EntityEvent {
  flecs::entity_t entity;
  EntityOp op;
  std::string name; // Store entity name for recreation
};

class StateHistory {
public:
  flecs::world *world;
  std::vector<Snapshot> snapshots;
  size_t keyframe_interval;
  bool enable_compression;

  // Current position in timeline (for temporal navigation)
  size_t current_frame;

  // Flag to disable event recording during rollback/restore operations
  bool recording_enabled;

  // Tracked component IDs and sizes (replaces template repetition)
  std::vector<ecs_entity_t> tracked_component_ids;
  std::vector<size_t> tracked_component_sizes;

  std::vector<ComponentEvent> frame_events;

  std::vector<RelationshipEvent> relationship_events;

  std::vector<EntityEvent> entity_events;

  // Track which entities exist (for keyframes and rollback)
  std::unordered_set<flecs::entity_t> tracked_entities;
  std::unordered_map<flecs::entity_t, std::string> entity_names;

  // TODO: What happens if there are multiple recreated entities that reuse an
  // id in a StateHistory? Map old entity IDs to new IDs during rollback (when
  // entities are recreated)
  std::unordered_map<flecs::entity_t, flecs::entity_t> entity_id_remap;

  // Previous frame cache: entity+component -> data
  std::unordered_map<uint64_t, std::vector<uint8_t>> prev_frame_state;

  // Component registry for sizes
  ComponentRegistry registry;

  StateHistory(flecs::world *w, size_t keyframe_every = 60,
               bool compress = true)
      : world(w), keyframe_interval(keyframe_every),
        enable_compression(compress), current_frame(0),
        recording_enabled(true) {}

  // Call this for each component type before calling setup_observers().
  template <typename T> void register_component() {
    flecs::entity_t id = world->component<T>().id();
    size_t size = sizeof(T);

    // Avoid duplicate registration
    if (std::find(tracked_component_ids.begin(), tracked_component_ids.end(),
                  id) == tracked_component_ids.end()) {
      tracked_component_ids.push_back(id);
      tracked_component_sizes.push_back(size);
      registry.register_component(id, size);
    }
  }

  void setup_observers();

  void record_event(flecs::entity_t entity, flecs::entity_t component,
                    ComponentOp op);

  void record_relationship(flecs::entity_t entity, flecs::entity_t relation,
                           flecs::entity_t target, ComponentOp op);

  void track_entity(flecs::entity e);

  void untrack_entity(flecs::entity e);

  std::vector<uint8_t> compress_buffer(const std::vector<uint8_t> &input);

  // Helper to combine all sections into single buffer
  struct SectionData {
    std::vector<uint8_t> data;
    uint32_t uncompressed_size;
    bool compressed;
  };

  void finalize_snapshot(Snapshot &snapshot,
                         const SectionData &component_section,
                         const SectionData &entity_section,
                         const SectionData &relationship_section);

  SectionData encode_and_compress_entities(
      const std::vector<std::pair<flecs::entity_t, std::string>>
          &entities_created,
      const std::vector<flecs::entity_t> &entities_destroyed,
      const std::unordered_set<flecs::entity_t> &existing_entities);

  void capture_state();

  void capture_all_components(Snapshot &snapshot,
                              std::vector<ComponentHeader> &headers,
                              std::vector<uint8_t> &data_section);

  SectionData capture_all_relationships();

  SectionData capture_changed_relationships();

  SectionData encode_and_compress_relationships(
      std::vector<RelationshipHeader> &relationships);

  void capture_changed_components(Snapshot &snapshot,
                                  std::vector<ComponentHeader> &headers,
                                  std::vector<uint8_t> &data_section);

  void capture_component_op(std::vector<ComponentHeader> &headers,
                            std::vector<uint8_t> &data_section,
                            flecs::entity_t entity, flecs::entity_t component,
                            const void *data, size_t size, ComponentOp op);

  void capture_component_diff(std::vector<ComponentHeader> &headers,
                              std::vector<uint8_t> &data_section,
                              flecs::entity_t entity_id,
                              flecs::entity_t component_id, const void *data,
                              size_t size);

  void rollback_to(size_t target_frame);

  // TODO: Consider only rolling forward a subset of
  // entities/components/relationship types to accelerate retroactive queries
  void roll_forward(size_t target_frame);

  void roll_to(size_t target_frame);

  void restore_entities_from_keyframe(size_t frame_idx);

  void clear_all_components();

  void clear_all_relationships();

  void restore_keyframe(size_t frame_idx);

  void apply_snapshot_forward(Snapshot &snapshot);

  void rebuild_prev_frame_state();

  uint64_t make_key(flecs::entity_t entity, flecs::entity_t component) const {
    return (static_cast<uint64_t>(entity) << 32) | component;
  }

  void print_stats();
};

// TODO: Migrate compression to TimelineHistory?
// If there are lots of branches, then each of those branches essentially become
struct TimelineNode {
  StateHistory *history;
  uint32_t branch_frame; // The frame of the StateHistory at which this timeline
                         // diverges...
  TimelineNode *parent;
  std::vector<TimelineNode *> children;
};

class TimelineTree {
public:
  TimelineNode *root_timeline;
  // Do we need to store an active timeline?
  // TimelineNode* active_timeline;
  size_t active_frame;

  void roll_to(TimelineNode *node, size_t target_frame);
};